### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/microbit-selfies#1]
Hi @lauraclay & @LornaLynch,

When you get a moment would you mind taking a look at this resource. Please don't worry about testing it (as that will be difficult without a microbit!) I'll ask one of the edu team to test it before we make it live. 

Please also be aware of the BBC micro:bit naming convention (see @MarcScott's guidance).

If I've made any major blunders in how I've written the copy then do let me know. It's been a while and I'm a little rusty! Thanks.

**Comment by lauraclay** [comment]
All done, although as per the comment I've left the URL blank for the 'Getting started with Raspberry Pi camera', in case I put the wrong link in!
