### ISSUE TITLE
Screenshot doesn't match code

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/microbit-selfies#7]
Only a minor issue (so feel free to close if you don't think it's worth fixing) but the code in the "PROGRAM THE RASPBERRY PI CAMERA" section doesn't match the screenshot - the code does `from time import sleep` whereas the screenshot does `import time`; and the code does `sleep(1)` whereas the screenshot does `time.sleep(5)`.

TBH I'm not sure why the sleep() is even needed in the first place? Maybe it was added as a side-effect of #6 ?

**Comment by lurch** [comment]
It's still `sleep(1)` in the code, and `sleep(5)` in the screenshot ;-)

**Comment by MarcScott** [comment]
I had a late night okay! :)
